### ISSUE TITLE
Web Server For Chrome Config

### ISSUE THREAD

**Issue by Licapor** [Licanpor/Crowdbotics_Challenge#1]
Install Web Server for Chrome extension on you browser.
Clone or download the repo on your computer.
Open the extension, click on CHOOSE A FOLDER and select the repo directory.
Then click on the Web Server URL that you prefer.
Done! now you are running the app.

![webserverconfig](https://user-images.githubusercontent.com/20423106/36071059-0419bd18-0ece-11e8-8894-0f23472c132e.png)

**Comment by Licanpor** [comment]
Install Web Server for Chrome extension on you browser.
Open it and CHOOSE A FOLDER to work and click on the Web Server URL that you prefer.
Done! now you can run your project.
